# Generated by Django 2.2.7 on 2019-11-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_auto_20191124_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='host_name',
            new_name='host',
        ),
    ]
