# Generated by Django 2.2.7 on 2019-11-24 13:47

from django.db import migrations, models
import ems.models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_auto_20191124_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.TimeField(default=ems.models.Visitor.get_default_my_time),
        ),
    ]
