# Generated by Django 2.2.7 on 2019-11-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_auto_20191124_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_name',
            field=models.CharField(max_length=200),
        ),
    ]
