# Generated by Django 2.2.7 on 2019-11-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_auto_20191125_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='host',
            field=models.CharField(max_length=200),
        ),
    ]
